<<<<<<< HEAD
name: build-ui-on-tag
on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip dist
        run: |
          cd dist
          zip -r ../budget-dashboard-ui-dist.zip .

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: budget-dashboard-ui-dist.zip
          generate_release_notes: true
=======
git add .github\workflows\release.yml
git commit -m "ci(ui): add build-on-tag release workflow"
git push
git tag v0.1.0
git push --tags
>>>>>>> d923605 (backup: 2025-09-20 17:48)
